spring:
  application:
    name: ppaibolsines

  datasource:
    url: jdbc:postgresql://localhost:5432/ppaibolsines
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true